// auth types
export const LOGOUT = 'LOGOUT';
export const AUTH_LOADING = 'AUTH_LOADING';
export const LOGIN = 'LOGIN';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const GET_APP_TOKEN = 'GET_APP_TOKEN';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const FORGET_REQUEST = 'FORGET_REQUEST';
export const RESET_REQUEST = 'RESET_REQUEST';
export const FORGET_SUCCESS = 'FORGET_SUCCESS';
export const RESET_SUCCESS = 'RESET_SUCCESS';
export const FORGET_FAILED = 'FORGET_FAILED';
export const RESET_FAILED = 'RESET_FAILED';
export const GET_APP_TOKEN_REQUEST = 'GET_APP_TOKEN_REQUEST';
export const SET_APP_TOKEN = 'SET_APP_TOKEN';
export const INITIAL_LOAD_REQUEST = 'INITIAL_LOAD_REQUEST';
