export const GET_CARTES_REQUEST = 'GET_CARTES_REQUEST';
export const GET_SINGLE_CARTE_REQUEST = 'GET_SINGLE_CARTE_REQUEST';
export const FILTER_CARTES_REQUEST = 'FILTER_CARTES_REQUEST';
export const GET_CARTES_LOADING = 'GET_CARTES_LOADING';
export const GET_SINGLE_CARTE_LOADING = 'GET_SINGLE_CARTE_LOADING';
export const SET_CARTES = 'SET_CARTES';
export const SET_CARTE = 'SET_CARTE';
