export const GET_WALLETS_REQUEST = 'GET_WALLETS_REQUEST';
export const FILTER_WALLETS_REQUEST = 'FILTER_WALLETS_REQUEST';
export const GET_WALLETS_LOADING = 'GET_WALLETS_LOADING';
export const SET_WALLETS = 'SET_WALLETS';
