
 const initialFValues = [
    {
      accessSignature :'',
      accessTag :'',
      accessUserId :'',
      accessUserIp :'',
      userTypeId  :'',
      userTag :'',
      parentUserId :'',
      parentType :'',
      specifiedUSPerson  :'',
      controllingPersonType :'',
      employeeType :'',
      entityType :'',
      title  :'',
      firstname :'',
      lastname  :'',
      middleNames :'',
      birthday  :'',
      email  :'',
      password :'',
      address1 :'',
      address2 :'' ,
      address3: '',
      postcode :'' ,
      postcode  :'',
      city   : '' ,
      state  : '' ,
      country  : '' ,
      phone   : '' ,
      mobile   : '' ,
      nationality   : '' ,
      nationalityOther  : '' ,
      placeOfBirth   : '' ,
      birthCountry   : '' ,
      occupation  : '' ,
      incomeRange   : '' ,
      legalName  : '' ,
      legalRegistrationNumber  : '' ,
      legalTvaNumber  : '' ,
      colegalRegistrationDateuntry  : '' ,
      legalForm  : '' ,
      legalShareCapital  : '' ,
      legalSector  : '' ,
      legalNetIncomeRange  : '' ,
      legalNumberOfEmployeeRange  : '' ,
      effectiveBeneficiary  : '' ,
      language  : '' ,
      taxNumber  : '' ,
      taxResidence  : '' ,
      activityOutsideEu  : '' ,
      position  : '' ,
      economicSanctions  : '' ,
      residentCountriesSanctions  : '' ,
      involvedSanctions  : '' ,
      timezone  : '' ,
    
    },
  ];

  export default initialFValues